# Generated by Django 4.0.6 on 2022-08-08 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-price'], 'verbose_name': 'phone'},
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('phones', 'phones'), ('computer', 'computer')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d', verbose_name='photos'),
        ),
        migrations.AlterField(
            model_name='products',
            name='content',
            field=models.TextField(blank=True, default='content', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='type the name', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
