# Generated by Django 4.0.6 on 2022-08-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_test_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'phone'},
        ),
    ]
