# Generated by Django 4.0.6 on 2022-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_video_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='watch',
            field=models.ManyToManyField(to='pages.video'),
        ),
    ]
